version: '2'
services:
    userprofile:
        image: userprofile
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
        ports:
            - 8081:8080
networks:
  default:
    external:
      name: erpsystem-microservices_default